name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List directory contents
        run: ls -R

      - name: Run Black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./format-cicd"  # Ensure this path is correct
