name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List directory contents
        run: ls -R

      - name: Run Black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./scripts" # Update the path to your scripts directory

      - name: Format code with Black
        if: failure()  # Only run this step if the previous Black step fails
        uses: psf/black@stable
        with:
          src: "./scripts"  # Automatically format code
