name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List directory contents
        run: ls -R

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version

      - name: Install dependencies
        run: |
          pip install sqlfluff black pylint autopep8
  
      - name: Check SQLFluff installation
        run: |
          pip show sqlfluff
          sqlfluff --version  # Check if sqlfluff is accessible

      - name: Format code with Autopep8
        run: |
          AUTOPEP8_SRC="./scripts"
          find $AUTOPEP8_SRC -name "*.py" -exec autopep8 --in-place {} +  # Format all Python files

      - name: Run PyLint
        run: |
          PYLINT_SRC="./scripts"
          find $PYLINT_SRC -name "*.py" -exec pylint {} +  # Lint all Python files

      - name: Run Black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./scripts"  # Update the path to your scripts directory

      - name: Format code with Black
        if: failure()  # Only run this step if the previous Black step fails
        uses: psf/black@stable
        with:
          src: "./scripts"  # Automatically format code

      - name: Lint SQL files with SQLFluff
        run: |
          SQL_SRC="./scripts"
          echo "Linting SQL files in $SQL_SRC"
          find $SQL_SRC -name "*.sql" -exec sqlfluff lint {} --dialect bigquery +  # Lint SQL files

      - name: Fix SQL files with SQLFluff
        if: failure()  # Only run this step if the previous SQLFluff lint step fails
        run: |
          SQL_SRC="./scripts"
          echo "Fixing SQL files in $SQL_SRC"
          find $SQL_SRC -name "*.sql" -exec sqlfluff fix {} --dialect bigquery +  # Automatically fix SQL formatting
